name: Review
on: [pull_request]
jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Review
        uses: Garlic-Team/Auto-Review@1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.TEST }}
          EVENT_TYPE: APPROVE
          MESSAGE: 'Everything is fine.'
